func:
  replicas: 2
  image: python-demo-app
  tag: init
  args:
    - '--bind'
    - '0.0.0.0'
    - 'app:app'
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  route:
    namespace: OVERRIDDEN
    containerPort: 8000
    portName: gunicorn
